
package com.store.presentation;

import java.awt.ComponentOrientation;
import java.util.List;

import com.store.database.exception.PersistanceOperationException;
import com.store.models.basic.BasicStoreEntity;
import com.store.models.impl.Customer;
import com.store.models.impl.Product;
import com.store.service.basic.BasicServiceManager;
import com.store.service.impl.CustomerService;
import com.store.service.impl.ProductService;
import com.store.ws.service.exception.OperationFailureException;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.JButton;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;


public class AddProduct extends javax.swing.JFrame {

   private BasicServiceManager basicServiceManager;
   
     private Product Product ;
     
	   private DefaultTableModel tableModel ;
	  SalesInvoice salesInvoicePresentation ;
	   
	   private List<BasicStoreEntity>  allProducts ;
	   String customerID ;
	   String customerName;
	   
	  
	   
    public AddProduct() throws PersistanceOperationException {
        initComponents();
        SelectProductMode();
//	    AllCustomersTable.addAncestorListener(this);
	    AllProductsTable.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
	    
	    setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
	    
	     
	    
	 
	
	 
  
    

    }
    
    public void SelectProductMode(){

		productName.setVisible(false);
    	  productCategory.setVisible(false);
    	  productLocation.setVisible(false);
    		productNameLabel.setVisible(false);
      	  productCategoryLabel.setVisible(false);
      	  productLocationLabel.setVisible(false);
    	   
    }
    
    public void AddProductMode(){

    	productName.setVisible(true);
  	  productCategory.setVisible(true);
  	  productLocation.setVisible(true);
  		productNameLabel.setVisible(true);
    	  productCategoryLabel.setVisible(true);
    	  productLocationLabel.setVisible(true);
  	   
//    	    AllCustomersTable.addAncestorListener(this);
    	  scrollPane.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @throws PersistanceOperationException 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws PersistanceOperationException {

        jPanel1 = new javax.swing.JPanel();
        productName = new javax.swing.JTextField();
        productCategory = new javax.swing.JTextField();
        productLocation = new javax.swing.JTextField();
        productNameLabel = new javax.swing.JLabel();
        productLocationLabel = new javax.swing.JLabel();
        productCategoryLabel = new javax.swing.JLabel();
        saveProduct = new javax.swing.JButton();
        addProduct = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setName(""); // NOI18N

        productName.setName("productName"); // NOI18N
        productName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameActionPerformed(evt);
            }
        });

        productCategory.setName("productCategory"); // NOI18N

        productLocation.setName("productLocation"); // NOI18N

        productNameLabel.setText("الصنف");

        productLocationLabel.setText("الموقع");

        productCategoryLabel.setText("التصنيف");

        saveProduct.setText("اضافة");
        saveProduct.setHideActionText(true);
        saveProduct.setName("Add"); // NOI18N
        saveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        
        addProduct.setText("إضافة منتج");
        String col[] = {"\u0631\u0642\u0645 \u0627\u0644\u0635\u0646\u0641", "\u0627\u0633\u0645 \u0627\u0644\u0635\u0646\u0641", "\u0627\u0644\u0648\u062D\u062F\u0629", "السعر","\u062F\u0627\u062E\u0644", "\u062E\u0627\u0631\u062C", "\u0627\u0644\u0631\u0635\u064A\u062F"};

	     tableModel = new DefaultTableModel(col, 0);
	
	    
	
	     basicServiceManager = new ProductService();
	    	
	allProducts = ((ProductService) basicServiceManager).allProducts();
	for (int i =0 ; i< allProducts.size(); i++ ){
		Product prod = (Product) allProducts.get(i);
	int prodIn = prod.getProductsIn();	
	int prodOut = prod.getProductsOut();
	int balence = prodIn - prodOut ;
	System.out.println(balence);
	
	System.out.println("Id"+prod.getId()); 
	System.out.println("Id"+prod.getProductsName());
	System.out.println("Id"+prod.getProductsUnit());
	System.out.println("Id"+ prod.getProductPrice());
	System.out.println("Id"+prod.getProductsIn());
	System.out.println("Id"+prod.getProductsOut());
		
		Object [] obj = {prod.getId(),prod.getProductsName(),prod.getProductsUnit(),prod.getProductPrice(),
				prod.getProductsIn(),prod.getProductsOut(),balence};

		tableModel.addRow( obj);
	}

        
        scrollPane = new JScrollPane();
        
        JButton addProduct = new JButton("إضافة منتج");
        addProduct.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		AddProductMode();
        	}
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap(203, Short.MAX_VALUE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(productCategory, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 183, GroupLayout.PREFERRED_SIZE)
        				.addComponent(productName, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 183, GroupLayout.PREFERRED_SIZE)
        				.addComponent(productLocation, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 183, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(productCategoryLabel, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
        				.addComponent(productNameLabel, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
        				.addComponent(productLocationLabel, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE))
        			.addGap(24))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(31)
        			.addComponent(addProduct)
        			.addContainerGap(365, Short.MAX_VALUE))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(21)
        			.addComponent(saveProduct, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 329, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(55)
        			.addComponent(addProduct)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(productName, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        				.addComponent(productNameLabel, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
        			.addGap(29)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(productCategory, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
        				.addComponent(productCategoryLabel, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE))
        			.addGap(29)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(productLocation, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        				.addComponent(productLocationLabel, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(saveProduct, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
        				.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 94, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap())
        );
        
        AllProductsTable = new JTable();
        AllProductsTable.addKeyListener(new KeyAdapter() {
        	@Override
        	public void keyPressed(KeyEvent arg0) {
        		
        		int row = AllProductsTable.getSelectedRow();
        		System.out.println("value  "+AllProductsTable.getModel().getValueAt(row, 0).toString());
//        		SalesInvoice.getCustomerNumber().setText( AllProductsTable.getModel().getValueAt(row, 0).toString());
//        		SalesInvoice.getCustomerName().setText(AllProductsTable.getModel().getValueAt(row, 1).toString());
//        		customerID = "123";
        		
        		
        		Object [] obj = {
        				AllProductsTable.getModel().getValueAt(row, 0),
        				AllProductsTable.getModel().getValueAt(row, 1).toString(),
        				AllProductsTable.getModel().getValueAt(row, 2).toString(),
        				AllProductsTable.getModel().getValueAt(row, 3).toString(),
        				AllProductsTable.getModel().getValueAt(row, 4).toString(),
        				AllProductsTable.getModel().getValueAt(row, 5).toString()};
        		
        		//SalesInvoice.getTableModel().addRow(obj);
        		
        		int rowCount = SalesInvoice.getTableModel().getRowCount();
        		Object id =  AllProductsTable.getModel().getValueAt(row, 0);
        		
        		System.out.println(id);
        		SalesInvoice.getTableModel().setValueAt(AllProductsTable.getModel().getValueAt(row, 0), rowCount-1, 0);
        		SalesInvoice.getTableModel().setValueAt(AllProductsTable.getModel().getValueAt(row, 1), rowCount-1, 1);
        		SalesInvoice.getTableModel().setValueAt(AllProductsTable.getModel().getValueAt(row, 2), rowCount-1, 3);
        		SalesInvoice.getTableModel().setValueAt(AllProductsTable.getModel().getValueAt(row, 3), rowCount-1, 4);
        		SalesInvoice.getTableModel().setValueAt(AllProductsTable.getModel().getValueAt(row, 0), rowCount-1, 0);
        		
        		
        		dispose();

        	}
        });
        AllProductsTable.setModel(tableModel);
        scrollPane.setViewportView(AllProductsTable);
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
    	
    	basicServiceManager = new ProductService();
    	Product = new Product();
    	Product.setProductsName(productName.getText());
    	Product.setProductsCategory(productCategory.getText());
    	Product.setProductsLocation(productLocation.getText());
    	
    	
    	try {
			basicServiceManager.insertNewItem(Product);
			productName.setText(""); 
	    	productCategory.setText("");
	    	productLocation.setText("");
	    	
	    	
tableModel.setRowCount(0);
			
Object [] obj = {Product.getId(),Product.getProductsName(),Product.getProductsUnit(),Product.getProductPrice(),Product.getProductsIn(),
		Product.getProductsOut(),(Product.getProductsIn() -  Product.getProductsOut())};

			tableModel.addRow( obj);
			
			SelectProductMode();
    	    
    	    scrollPane.setVisible(true);
		} catch (OperationFailureException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	
    	
    }//GEN-LAST:event_saveActionPerformed

    private void productNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
					new AddProduct().setVisible(true);
				} catch (PersistanceOperationException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JLabel productLocationLabel;
    private javax.swing.JLabel productCategoryLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField productCategory;
    private javax.swing.JTextField productLocation;
    private javax.swing.JTextField productName;
    private javax.swing.JButton saveProduct;
    private javax.swing.JButton addProduct;
    
    private JScrollPane scrollPane;
    private JTable AllProductsTable;
}
